import type { GenerationTask } from "./types";

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

function completedSecondsAfter(createdAt: string, seconds: number): string {
  return new Date(new Date(createdAt).getTime() + seconds * 1000).toISOString();
}

export function seedGenerationTasks(): GenerationTask[] {
  return [
    {
      id: "seed-1",
      type: "image",
      status: "running",
      prompt: "Photorealistic portrait of a young woman, soft studio lighting, shallow depth of field",
      createdAt: minutesAgo(12),
      providerId: "midjourney",
      modelId: "7",
      modelLabel: "Midjourney v7",
      credits: 80,
      estimatedMinutes: 1,
      estimatedSeconds: 30,
      progress: 42,
    },
    {
      id: "seed-2",
      type: "video",
      status: "running",
      prompt: "Cinematic establishing shot, golden hour lighting, anamorphic lens flare",
      createdAt: minutesAgo(18),
      providerId: "kling",
      modelId: "kling-3.0",
      modelLabel: "Kling 3.0",
      credits: 75,
      estimatedMinutes: 1,
      estimatedSeconds: 60,
      progress: 28,
    },
    {
      id: "seed-3",
      type: "text",
      status: "queued",
      prompt: "Напиши вирусный пост для Telegram про запуск нового AI-продукта",
      createdAt: minutesAgo(5),
      providerId: "chatgpt",
      modelId: "gpt-5.2",
      modelLabel: "GPT 5.2",
      credits: 6,
      estimatedMinutes: 2,
      estimatedSeconds: 120,
      progress: 0,
    },
    {
      id: "seed-4",
      type: "audio",
      status: "queued",
      prompt: "Энергичный поп-трек для рекламы, позитивное настроение, запоминающийся припев",
      createdAt: minutesAgo(4),
      providerId: "suno",
      modelId: "v5",
      modelLabel: "Suno v5",
      credits: 30,
      estimatedMinutes: 2,
      estimatedSeconds: 90,
      progress: 0,
    },
    {
      id: "seed-5",
      type: "image",
      status: "queued",
      prompt: "Minimal flat vector logo design for a fintech startup, clean lines",
      createdAt: minutesAgo(3),
      providerId: "flux",
      modelId: "flux-kontext-pro",
      modelLabel: "Flux Kontext Pro",
      credits: 15,
      estimatedMinutes: 1,
      estimatedSeconds: 15,
      progress: 0,
    },
    {
      id: "seed-6",
      type: "video",
      status: "queued",
      prompt: "Trendy vertical video for Reels, vibrant colors, social media optimized",
      createdAt: minutesAgo(2),
      providerId: "veo",
      modelId: "veo-3",
      modelLabel: "Veo 3",
      credits: 120,
      estimatedMinutes: 2,
      estimatedSeconds: 120,
      progress: 0,
    },
    {
      id: "seed-7",
      type: "text",
      status: "done",
      prompt: "Составь бизнес-план для онлайн-школы по нейросетям на 12 месяцев",
      createdAt: minutesAgo(45),
      completedAt: completedSecondsAfter(minutesAgo(45), 8),
      providerId: "claude",
      modelId: "opus-4.5",
      modelLabel: "Claude Opus 4.5",
      credits: 3,
      estimatedMinutes: 2,
      estimatedSeconds: 120,
      progress: 100,
    },
    {
      id: "seed-8",
      type: "image",
      status: "done",
      prompt: "Cyberpunk neon city scene with holographic billboards, blade runner atmosphere",
      createdAt: minutesAgo(38),
      completedAt: completedSecondsAfter(minutesAgo(38), 12),
      providerId: "nano-banana",
      modelId: "banana-2",
      modelLabel: "Nano Banana 2",
      credits: 300,
      estimatedMinutes: 1,
      estimatedSeconds: 30,
      progress: 100,
    },
    {
      id: "seed-9",
      type: "audio",
      status: "done",
      prompt: "Добрый день! Представляем вам новый продукт, который изменит ваш подход к работе.",
      createdAt: minutesAgo(30),
      completedAt: completedSecondsAfter(minutesAgo(30), 18),
      providerId: "elevenlabs",
      modelId: "eleven-v2",
      modelLabel: "Eleven v2",
      credits: 60,
      estimatedMinutes: 1,
      estimatedSeconds: 30,
      progress: 100,
    },
    {
      id: "seed-10",
      type: "video",
      status: "failed",
      prompt: "Product showcase commercial, smooth camera movement, premium lighting",
      createdAt: minutesAgo(25),
      providerId: "sora",
      modelId: "sora-2",
      modelLabel: "Sora 2",
      credits: 480,
      estimatedMinutes: 3,
      estimatedSeconds: 180,
      progress: 61,
      errorMessage: "Недостаточно кредитов",
    },
    {
      id: "seed-11",
      type: "image",
      status: "failed",
      prompt: "Anime style character illustration, vibrant colors, dynamic pose",
      createdAt: minutesAgo(20),
      providerId: "seedream",
      modelId: "seedream-5-lite",
      modelLabel: "Seedream 5 Lite",
      credits: 2,
      estimatedMinutes: 1,
      estimatedSeconds: 10,
      progress: 34,
      errorMessage: "Модель временно недоступна",
    },
    {
      id: "seed-12",
      type: "text",
      status: "canceled",
      prompt: "Переведи на английский техническую документацию по API интеграции",
      createdAt: minutesAgo(15),
      providerId: "gemini",
      modelId: "gemini-2.5-pro",
      modelLabel: "Gemini 2.5 Pro",
      credits: 1,
      estimatedMinutes: 1,
      estimatedSeconds: 60,
      progress: 12,
      errorMessage: "Отменено пользователем",
    },
  ];
}
